layout: sidebar
style: light
description: "Using metallurgical-based metaheuristics as a metaphor for life. This product may contain: technology, design, societal consequences, gender issues, and occasional humor."
author: 
  name: Vivian Qu

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
  - jekyll-feed

permalink: /blog/:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "assets/img"
    values:
      image: true

repos:
  show_on_home: false
  sort_by: stars
  limit: 9
  exclude:
    forks: true

social_media:
  twitter: vivqu
  medium: vivqu
  pinterest: vivqu
  instagram: skwishum

projects:
  - name: WorldAnimals
    web_url: https://worldanimalsapp.com
    image_url: assets/img/worldanimals_icon.png
    description: Does a dog say "woof" in Chinese?

  - name: Haiku
    web_url: https://itunes.apple.com/us/app/haiku-simple-writing-app-for-haikus/id1227312972?mt=8&ign-mpt=uo%3D4
    image_url: assets/img/haiku_icon.png
    description: Writing poems with ease

  - name: San Fransokyo
    web_url: https://www.sanfransokyopodcast.com/
    image_url: assets/img/san_fransokyo_logo.png
    image_size: 100
    description: An American podcast abroad in Japan

email_address: hello@vivqu.com
twitter_username: vivqu
github_username: vivqu
instagram_username: skwishum
pinterest_username: vivqu
linkedin_username: vivqu
